use_frameworks!

platform :ios, '10.0'

target 'MKLoRaWAN-AF_Example' do
  pod 'MKLoRaWAN-AF', :path => '../'

  target 'MKLoRaWAN-AF_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
